# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mondayUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mondayUi(object):
    def setupUi(self, mondayUi):
        mondayUi.setObjectName("mondayUi")
        mondayUi.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(mondayUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1431, 891))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/7LP8.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1140, 820, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 10);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1250, 820, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 401, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/T8bahf.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(670, 40, 331, 61))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1000, 40, 331, 61))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        mondayUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(mondayUi)
        QtCore.QMetaObject.connectSlotsByName(mondayUi)

    def retranslateUi(self, mondayUi):
        _translate = QtCore.QCoreApplication.translate
        mondayUi.setWindowTitle(_translate("mondayUi", "MainWindow"))
        self.pushButton.setText(_translate("mondayUi", "Run"))
        self.pushButton_2.setText(_translate("mondayUi", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mondayUi = QtWidgets.QMainWindow()
    ui = Ui_mondayUi()
    ui.setupUi(mondayUi)
    mondayUi.show()
    sys.exit(app.exec_())
